heat_template_version: 2015-04-30

description: >
  Trove controller node configured by Puppet

parameters:
  servers:
    type: json

resources:

  TroveDeployment:
    type: OS::Heat::SoftwareDeployment
    properties:
      config: {get_resource: TroveConfig}
      server: {get_param: servers}

  # Map heat metadata into hiera datafiles
  TroveConfig:
    type: OS::Heat::SoftwareConfig
    properties:
      group: puppet
      options: 
        enable_hiera: True
        enable_facter: False
      inputs: 
      config:
        get_file: /home/stack/templates/puppet/manifests/osp7-controller-trove-pacemaker.pp


